name: jojo_sdk
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  appmetrica_plugin: ^1.4.0
  centrifuge: ^0.11.0
  device_info_plus: ^9.0.2
  flutter:
    sdk: flutter
  flutter_easy_dialogs: 3.1.2
  freezed: ^2.4.0
  freezed_annotation: ^2.2.0
  geolocator: ^10.1.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  jojo_ui_kit:
    path: ../jojo_ui_kit
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  neo_image_editor:
    path: ../neo_image_editor
  permission_handler: ^11.1.0
  photo_view: ^0.14.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.12
  xander9112:
    git:
      url: https://github.com/xander9112/flutter_xander9112
      ref: 0.0.5
dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  intl_utils: ^2.8.6
  openapi_generator: ^4.10.0
  retrofit_generator: ^8.0.4
  very_good_analysis: ^5.1.0

flutter: null
