name: jojo
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+47

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  anchor_scroll_controller: ^0.4.4
  app_settings: 5.0.0
  async_queue: 1.3.0
  camera: 0.10.5+4
  carousel_slider: ^4.2.1
  centrifuge: ^0.11.0
  clipboard: 0.1.3
  crypto: 3.0.3
  cupertino_icons: 1.0.6
  firebase_auth: 4.9.0
  firebase_core: 2.15.1
  firebase_crashlytics: 3.3.5
  firebase_messaging: 14.6.7
  flutter:
    sdk: flutter
  flutter_easy_dialogs: 3.1.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_svg: 2.0.7
  freezed: ^2.4.0
  freezed_annotation: ^2.2.0
  geolocator: ^10.1.0
  get_it: 7.6.4
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.2
  image_crop: ^0.4.1
  injectable: ^2.1.2
  intl: ^0.18.0
  jojo_menu:
    path: ./packages/jojo_menu
  jojo_sdk:
    path: ./packages/jojo_sdk
  jojo_supporting:
    path: ./packages/jojo_supporting
  jojo_ui_kit:
    path: ./packages/jojo_ui_kit
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lottie: ^2.4.0
  neo_image_editor:
    path: ./packages/neo_image_editor
  openapi_generator_annotations: ^4.10.0
  path_provider: ^2.0.15
  permission_handler: ^11.1.0
  photo_manager: ^2.6.0
  pretty_dio_logger: ^1.3.1
  reactive_forms: ^16.0.1
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.0
  sign_in_with_apple: ^5.0.0
  stream_transform: ^2.1.0
  swipe_refresh: ^1.0.2
  url_launcher: ^6.1.12
  uuid: ^4.2.1
  x_logger:
    path: ./packages/x_logger

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: 2.4.6
  cli_dialog: ^0.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  intl_utils: ^2.8.3
  openapi_generator: ^4.10.0
  process_run: ^0.13.1
  pubspec_yaml: ^3.1.0
  retrofit_generator: ^7.0.8
  very_good_analysis: ^5.0.0+1
  yaml: ^3.1.2
  yaml_writer: ^1.0.3

# dependency_overrides:
# build_resolvers: 2.2.1
#временно, ждем офф фикс для iOS 17 https://github.com/pichillilorenzo/flutter_inappwebview/issues/1735
# flutter_inappwebview:
#   git:
#     url: https://github.com/Estrelio/flutter_inappwebview.git
#     ref: fix-xcode-17
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
