name: jojo_ui_kit
description: JoJo UI Kit.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  cached_network_image: ^3.3.0
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  lottie: ^2.4.0
  mask_text_input_formatter: ^2.4.0
  reactive_forms: ^16.0.1
  reorderable_grid_view: ^2.2.7
  skeletons: ^0.0.3
  swipe_refresh: ^1.0.2
  transparent_image: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  assets:
    - assets_old/images_old/
    - assets_old/images_old/alert/
    - assets_old/images_old/avatar/
    - assets_old/images_old/dialogs/
    - assets_old/images_old/chat/
    - assets_old/images_old/profile/
    - assets_old/images_old/registration/
    - assets_old/images_old/liked/
    - assets_old/images_old/story/
    - assets_old/images_old/menu/
    - assets_old/icons_old/
    - assets_old/icons_old/alerts/
    - assets_old/icons_old/zodiacs/
    - assets_old/icons_old/ratingStars/
    - assets_old/media/
    - assets/images/
    - assets/images/about/
    - assets/images/alert/
    - assets/images/empty_states/
    - assets/images/onboarding/
    - assets/images/other/
    - assets/images/logos/
    - assets/images/registration/
    - assets/icons/
    - assets/media/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 900
        - asset: fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 900
          style: italic
    - family: AvenirNextCyr
      fonts:
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-Thin.ttf
          weight: 100
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-UltraLight.ttf
          weight: 200
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-UltraLightIt.ttf
          weight: 200
          style: italic
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-Light.ttf
          weight: 300
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-Regular.ttf
          weight: 400
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-Medium.ttf
          weight: 500
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-Demi.ttf
          weight: 600
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-DemiItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-Bold.ttf
          weight: 700
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-Heavy.ttf
          weight: 800
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-Heavy.ttf
          weight: 900
        - asset: fonts/avenyrnextcyr/AvenirNextCyr-HeavyItalic.ttf
          weight: 900
          style: italic
