name: jojo_supporting
description: JoJo Supporting
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_settings: ^5.0.0

  clipboard: ^0.1.3

  cupertino_icons: ^1.0.5

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter

  freezed: ^2.4.0
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.2
  injectable: ^2.1.2
  intl: 0.18.1
  jojo_sdk:
    path: "../jojo_sdk"
  jojo_ui_kit:
    path: "../jojo_ui_kit"
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  openapi_generator_annotations: ^4.10.0
  path_provider: ^2.0.15
  retrofit: ^4.0.1
  shared_preferences: ^2.2.0
  stream_transform: ^2.1.0
  swipe_refresh: ^1.0.2
  url_launcher: ^6.1.12
  x_logger:
    path: ../x_logger

dev_dependencies:
  auto_route_generator: 7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  intl_utils: ^2.8.3
  openapi_generator: ^4.10.0
  retrofit_generator: ^7.0.8
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  build_resolvers: 2.2.1

flutter: null
