name: jojo_menu
description: JoJo Menu
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_settings: ^5.0.0
  auto_route: 7.8.4
  bloc: ^8.1.2
  clipboard: ^0.1.3
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^6.0.0-beta.25
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  freezed: ^2.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.2
  injectable: ^2.1.2
  intl: 0.18.1
  in_app_review: ^2.0.8
  jojo_sdk:
    path: "../jojo_sdk"
  jojo_supporting:
    path: "../jojo_supporting"
  jojo_ui_kit:
    path: "../jojo_ui_kit"
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  openapi_generator_annotations: ^4.10.0
  path_provider: ^2.0.15
  reactive_forms: ^16.0.1
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  stream_transform: ^2.1.0
  swipe_refresh: ^1.0.2
  url_launcher: ^6.1.12

dev_dependencies:
  auto_route_generator: 7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.1.6
  intl_utils: ^2.8.3
  openapi_generator: ^4.10.0
  retrofit_generator: ^7.0.8
  very_good_analysis: ^5.0.0+1

flutter: null
