// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;
import 'package:xander9112/xander9112.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform(EnvConfig env) {
    final bool isDev = env == EnvConfig.dev;

    if (kIsWeb) {
      return isDev ? webDev : web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return isDev ? androidDev : android;
      case TargetPlatform.iOS:
        return isDev ? iosDev : ios;
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc15vil5M31OTF7BFvWoyZJU0opSLrLhg',
    appId: '1:749604079661:web:514ef20cd06f6a790910a4',
    messagingSenderId: '749604079661',
    projectId: 'jojo-authenticate',
    authDomain: 'jojo-authenticate.firebaseapp.com',
    storageBucket: 'jojo-authenticate.appspot.com',
    measurementId: 'G-DY8VE2D7VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCznPcoU9LPQ0EZl3iC3m9SaTiqLnsxGdM',
    appId: '1:749604079661:android:7febc294dcd31bc00910a4',
    messagingSenderId: '749604079661',
    projectId: 'jojo-authenticate',
    storageBucket: 'jojo-authenticate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMSN-kJy_a4lNFxQ3M_ZBRsCC2973vuOk',
    appId: '1:749604079661:ios:ba63d6ef075bb1e50910a4',
    messagingSenderId: '749604079661',
    projectId: 'jojo-authenticate',
    storageBucket: 'jojo-authenticate.appspot.com',
    iosClientId:
        '749604079661-mtvn3prvdcqg15ob2l6f4g9dt7rv2a77.apps.googleusercontent.com',
    iosBundleId: 'com.dating.jojo',
  );

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyCjWVT7el6atzCxpHVzHL2JoJedTWP9W6o',
    appId: '1:366442298722:web:03ace5629b65a5abcd403b',
    messagingSenderId: '366442298722',
    projectId: 'jojo-authenticate-dev',
    authDomain: 'jojo-authenticate-dev.firebaseapp.com',
    storageBucket: 'jojo-authenticate-dev.appspot.com',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyAbsSyGoNLq9c87O3jiCaRzC6z12_Hjyhc',
    appId: '1:366442298722:android:d864fe076cec5888cd403b',
    messagingSenderId: '366442298722',
    projectId: 'jojo-authenticate-dev',
    storageBucket: 'jojo-authenticate-dev.appspot.com',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyDiJmZCqSSdoKVWZsO9F2gR-Y5dkb6Gef4',
    appId: '1:366442298722:ios:286e4613e10bce4ecd403b',
    messagingSenderId: '366442298722',
    projectId: 'jojo-authenticate-dev',
    storageBucket: 'jojo-authenticate-dev.appspot.com',
    iosClientId:
        '366442298722-ossru2nid4lrsam8gdn48qn6ks7760n5.apps.googleusercontent.com',
    iosBundleId: 'com.dating.jojo.dev',
  );
}
