name: neo_image_editor
description: Neoflex Image Editor
version: 1.0.2
homepage: "neoflex.ru"

publish_to: none

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  anchor_scroll_controller: ^0.4.3
  camera: ^0.10.5+2
  camera_web: ^0.3.1+4
  camera_windows: ^0.2.1+7
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_draggable_gridview: ^0.0.8
  flutter_image_compress: ^2.0.3
  flutter_isolate: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.2.1
  image: ^4.1.3
  image_picker: ^1.0.1
  image_picker_windows: ^0.2.1
  intl: 0.18.1
  jojo_ui_kit:
    path: ../jojo_ui_kit
  path_provider: ^2.0.15
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
